INSERT INTO UsuariosDAW(usuario) VALUES (aldij_1daw);
CREATE DATABASE bdaldije_1daw;
GRANT ALL PRIVILEGES ON bdaldije_1daw.* TO 'aldij_1daw'@'localhost' IDENTIFIED BY 'aldij_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (aldoc_1daw);
CREATE DATABASE bdaldoco_1daw;
GRANT ALL PRIVILEGES ON bdaldoco_1daw.* TO 'aldoc_1daw'@'localhost' IDENTIFIED BY 'aldoc_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (amvar_1daw);
CREATE DATABASE bdamvara_1daw;
GRANT ALL PRIVILEGES ON bdamvara_1daw.* TO 'amvar_1daw'@'localhost' IDENTIFIED BY 'amvar_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (bucra_1daw);
CREATE DATABASE bdbucral_1daw;
GRANT ALL PRIVILEGES ON bdbucral_1daw.* TO 'bucra_1daw'@'localhost' IDENTIFIED BY 'bucra_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (cablj_1daw);
CREATE DATABASE bdcablju_1daw;
GRANT ALL PRIVILEGES ON bdcablju_1daw.* TO 'cablj_1daw'@'localhost' IDENTIFIED BY 'cablj_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (caced_1daw);
CREATE DATABASE bdcaceda_1daw;
GRANT ALL PRIVILEGES ON bdcaceda_1daw.* TO 'caced_1daw'@'localhost' IDENTIFIED BY 'caced_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (camua_1daw);
CREATE DATABASE bdcamuad_1daw;
GRANT ALL PRIVILEGES ON bdcamuad_1daw.* TO 'camua_1daw'@'localhost' IDENTIFIED BY 'camua_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (cales_1daw);
CREATE DATABASE bdcalese_1daw;
GRANT ALL PRIVILEGES ON bdcalese_1daw.* TO 'cales_1daw'@'localhost' IDENTIFIED BY 'cales_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (chraj_1daw);
CREATE DATABASE bdchraje_1daw;
GRANT ALL PRIVILEGES ON bdchraje_1daw.* TO 'chraj_1daw'@'localhost' IDENTIFIED BY 'chraj_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (diolo_1daw);
CREATE DATABASE bddiolos_1daw;
GRANT ALL PRIVILEGES ON bddiolos_1daw.* TO 'diolo_1daw'@'localhost' IDENTIFIED BY 'diolo_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (escaj_1daw);
CREATE DATABASE bdescaju_1daw;
GRANT ALL PRIVILEGES ON bdescaju_1daw.* TO 'escaj_1daw'@'localhost' IDENTIFIED BY 'escaj_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (gavaj_1daw);
CREATE DATABASE bdgavajo_1daw;
GRANT ALL PRIVILEGES ON bdgavajo_1daw.* TO 'gavaj_1daw'@'localhost' IDENTIFIED BY 'gavaj_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (golee_1daw);
CREATE DATABASE bdgoleel_1daw;
GRANT ALL PRIVILEGES ON bdgoleel_1daw.* TO 'golee_1daw'@'localhost' IDENTIFIED BY 'golee_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (gopej_1daw);
CREATE DATABASE bdgopejo_1daw;
GRANT ALL PRIVILEGES ON bdgopejo_1daw.* TO 'gopej_1daw'@'localhost' IDENTIFIED BY 'gopej_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (govem_1daw);
CREATE DATABASE bdgovema_1daw;
GRANT ALL PRIVILEGES ON bdgovema_1daw.* TO 'govem_1daw'@'localhost' IDENTIFIED BY 'govem_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (gucal_1daw);
CREATE DATABASE bdgucalu_1daw;
GRANT ALL PRIVILEGES ON bdgucalu_1daw.* TO 'gucal_1daw'@'localhost' IDENTIFIED BY 'gucal_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (guloa_1daw);
CREATE DATABASE bdguloal_1daw;
GRANT ALL PRIVILEGES ON bdguloal_1daw.* TO 'guloa_1daw'@'localhost' IDENTIFIED BY 'guloa_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (gulod_1daw);
CREATE DATABASE bdguloda_1daw;
GRANT ALL PRIVILEGES ON bdguloda_1daw.* TO 'gulod_1daw'@'localhost' IDENTIFIED BY 'gulod_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (jusav_1daw);
CREATE DATABASE bdjusava_1daw;
GRANT ALL PRIVILEGES ON bdjusava_1daw.* TO 'jusav_1daw'@'localhost' IDENTIFIED BY 'jusav_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (leala_1daw);
CREATE DATABASE bdlealan_1daw;
GRANT ALL PRIVILEGES ON bdlealan_1daw.* TO 'leala_1daw'@'localhost' IDENTIFIED BY 'leala_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (mapej_1daw);
CREATE DATABASE bdmapeja_1daw;
GRANT ALL PRIVILEGES ON bdmapeja_1daw.* TO 'mapej_1daw'@'localhost' IDENTIFIED BY 'mapej_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (mopae_1daw);
CREATE DATABASE bdmopaes_1daw;
GRANT ALL PRIVILEGES ON bdmopaes_1daw.* TO 'mopae_1daw'@'localhost' IDENTIFIED BY 'mopae_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (mugoc_1daw);
CREATE DATABASE bdmugoch_1daw;
GRANT ALL PRIVILEGES ON bdmugoch_1daw.* TO 'mugoc_1daw'@'localhost' IDENTIFIED BY 'mugoc_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (pearj_1daw);
CREATE DATABASE bdpearju_1daw;
GRANT ALL PRIVILEGES ON bdpearju_1daw.* TO 'pearj_1daw'@'localhost' IDENTIFIED BY 'pearj_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (qumoj_1daw);
CREATE DATABASE bdqumojo_1daw;
GRANT ALL PRIVILEGES ON bdqumojo_1daw.* TO 'qumoj_1daw'@'localhost' IDENTIFIED BY 'qumoj_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (romom_1daw);
CREATE DATABASE bdromoma_1daw;
GRANT ALL PRIVILEGES ON bdromoma_1daw.* TO 'romom_1daw'@'localhost' IDENTIFIED BY 'romom_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (rualj_1daw);
CREATE DATABASE bdrualja_1daw;
GRANT ALL PRIVILEGES ON bdrualja_1daw.* TO 'rualj_1daw'@'localhost' IDENTIFIED BY 'rualj_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (sasap_1daw);
CREATE DATABASE bdsasapa_1daw;
GRANT ALL PRIVILEGES ON bdsasapa_1daw.* TO 'sasap_1daw'@'localhost' IDENTIFIED BY 'sasap_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (satel_1daw);
CREATE DATABASE bdsatelu_1daw;
GRANT ALL PRIVILEGES ON bdsatelu_1daw.* TO 'satel_1daw'@'localhost' IDENTIFIED BY 'satel_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (tovev_1daw);
CREATE DATABASE bdtoveve_1daw;
GRANT ALL PRIVILEGES ON bdtoveve_1daw.* TO 'tovev_1daw'@'localhost' IDENTIFIED BY 'tovev_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (varoa_1daw);
CREATE DATABASE bdvaroal_1daw;
GRANT ALL PRIVILEGES ON bdvaroal_1daw.* TO 'varoa_1daw'@'localhost' IDENTIFIED BY 'varoa_1daw';
INSERT INTO UsuariosDAW(usuario) VALUES (vemua_1daw);
CREATE DATABASE bdvemual_1daw;
GRANT ALL PRIVILEGES ON bdvemual_1daw.* TO 'vemua_1daw'@'localhost' IDENTIFIED BY 'vemua_1daw';
