CREATE USER 'aldij_1daw'@'localhost' IDENTIFIED BY 'aldij_1daw';CREATE DATABASE bdaldije_1daw;
GRANT ALL PRIVILEGES ON bdaldije_1daw.* TO 'aldij_1daw'@'localhost' IDENTIFIED BY 'aldij_1daw';
CREATE USER 'aldoc_1daw'@'localhost' IDENTIFIED BY 'aldoc_1daw';CREATE DATABASE bdaldoco_1daw;
GRANT ALL PRIVILEGES ON bdaldoco_1daw.* TO 'aldoc_1daw'@'localhost' IDENTIFIED BY 'aldoc_1daw';
CREATE USER 'amvar_1daw'@'localhost' IDENTIFIED BY 'amvar_1daw';CREATE DATABASE bdamvara_1daw;
GRANT ALL PRIVILEGES ON bdamvara_1daw.* TO 'amvar_1daw'@'localhost' IDENTIFIED BY 'amvar_1daw';
CREATE USER 'bucra_1daw'@'localhost' IDENTIFIED BY 'bucra_1daw';CREATE DATABASE bdbucral_1daw;
GRANT ALL PRIVILEGES ON bdbucral_1daw.* TO 'bucra_1daw'@'localhost' IDENTIFIED BY 'bucra_1daw';
CREATE USER 'cablj_1daw'@'localhost' IDENTIFIED BY 'cablj_1daw';CREATE DATABASE bdcablju_1daw;
GRANT ALL PRIVILEGES ON bdcablju_1daw.* TO 'cablj_1daw'@'localhost' IDENTIFIED BY 'cablj_1daw';
CREATE USER 'caced_1daw'@'localhost' IDENTIFIED BY 'caced_1daw';CREATE DATABASE bdcaceda_1daw;
GRANT ALL PRIVILEGES ON bdcaceda_1daw.* TO 'caced_1daw'@'localhost' IDENTIFIED BY 'caced_1daw';
CREATE USER 'camua_1daw'@'localhost' IDENTIFIED BY 'camua_1daw';CREATE DATABASE bdcamuad_1daw;
GRANT ALL PRIVILEGES ON bdcamuad_1daw.* TO 'camua_1daw'@'localhost' IDENTIFIED BY 'camua_1daw';
CREATE USER 'cales_1daw'@'localhost' IDENTIFIED BY 'cales_1daw';CREATE DATABASE bdcalese_1daw;
GRANT ALL PRIVILEGES ON bdcalese_1daw.* TO 'cales_1daw'@'localhost' IDENTIFIED BY 'cales_1daw';
CREATE USER 'chraj_1daw'@'localhost' IDENTIFIED BY 'chraj_1daw';CREATE DATABASE bdchraje_1daw;
GRANT ALL PRIVILEGES ON bdchraje_1daw.* TO 'chraj_1daw'@'localhost' IDENTIFIED BY 'chraj_1daw';
CREATE USER 'diolo_1daw'@'localhost' IDENTIFIED BY 'diolo_1daw';CREATE DATABASE bddiolos_1daw;
GRANT ALL PRIVILEGES ON bddiolos_1daw.* TO 'diolo_1daw'@'localhost' IDENTIFIED BY 'diolo_1daw';
CREATE USER 'escaj_1daw'@'localhost' IDENTIFIED BY 'escaj_1daw';CREATE DATABASE bdescaju_1daw;
GRANT ALL PRIVILEGES ON bdescaju_1daw.* TO 'escaj_1daw'@'localhost' IDENTIFIED BY 'escaj_1daw';
CREATE USER 'gavaj_1daw'@'localhost' IDENTIFIED BY 'gavaj_1daw';CREATE DATABASE bdgavajo_1daw;
GRANT ALL PRIVILEGES ON bdgavajo_1daw.* TO 'gavaj_1daw'@'localhost' IDENTIFIED BY 'gavaj_1daw';
CREATE USER 'golee_1daw'@'localhost' IDENTIFIED BY 'golee_1daw';CREATE DATABASE bdgoleel_1daw;
GRANT ALL PRIVILEGES ON bdgoleel_1daw.* TO 'golee_1daw'@'localhost' IDENTIFIED BY 'golee_1daw';
CREATE USER 'gopej_1daw'@'localhost' IDENTIFIED BY 'gopej_1daw';CREATE DATABASE bdgopejo_1daw;
GRANT ALL PRIVILEGES ON bdgopejo_1daw.* TO 'gopej_1daw'@'localhost' IDENTIFIED BY 'gopej_1daw';
CREATE USER 'govem_1daw'@'localhost' IDENTIFIED BY 'govem_1daw';CREATE DATABASE bdgovema_1daw;
GRANT ALL PRIVILEGES ON bdgovema_1daw.* TO 'govem_1daw'@'localhost' IDENTIFIED BY 'govem_1daw';
CREATE USER 'gucal_1daw'@'localhost' IDENTIFIED BY 'gucal_1daw';CREATE DATABASE bdgucalu_1daw;
GRANT ALL PRIVILEGES ON bdgucalu_1daw.* TO 'gucal_1daw'@'localhost' IDENTIFIED BY 'gucal_1daw';
CREATE USER 'guloa_1daw'@'localhost' IDENTIFIED BY 'guloa_1daw';CREATE DATABASE bdguloal_1daw;
GRANT ALL PRIVILEGES ON bdguloal_1daw.* TO 'guloa_1daw'@'localhost' IDENTIFIED BY 'guloa_1daw';
CREATE USER 'gulod_1daw'@'localhost' IDENTIFIED BY 'gulod_1daw';CREATE DATABASE bdguloda_1daw;
GRANT ALL PRIVILEGES ON bdguloda_1daw.* TO 'gulod_1daw'@'localhost' IDENTIFIED BY 'gulod_1daw';
CREATE USER 'jusav_1daw'@'localhost' IDENTIFIED BY 'jusav_1daw';CREATE DATABASE bdjusava_1daw;
GRANT ALL PRIVILEGES ON bdjusava_1daw.* TO 'jusav_1daw'@'localhost' IDENTIFIED BY 'jusav_1daw';
CREATE USER 'leala_1daw'@'localhost' IDENTIFIED BY 'leala_1daw';CREATE DATABASE bdlealan_1daw;
GRANT ALL PRIVILEGES ON bdlealan_1daw.* TO 'leala_1daw'@'localhost' IDENTIFIED BY 'leala_1daw';
CREATE USER 'mapej_1daw'@'localhost' IDENTIFIED BY 'mapej_1daw';CREATE DATABASE bdmapeja_1daw;
GRANT ALL PRIVILEGES ON bdmapeja_1daw.* TO 'mapej_1daw'@'localhost' IDENTIFIED BY 'mapej_1daw';
CREATE USER 'mopae_1daw'@'localhost' IDENTIFIED BY 'mopae_1daw';CREATE DATABASE bdmopaes_1daw;
GRANT ALL PRIVILEGES ON bdmopaes_1daw.* TO 'mopae_1daw'@'localhost' IDENTIFIED BY 'mopae_1daw';
CREATE USER 'mugoc_1daw'@'localhost' IDENTIFIED BY 'mugoc_1daw';CREATE DATABASE bdmugoch_1daw;
GRANT ALL PRIVILEGES ON bdmugoch_1daw.* TO 'mugoc_1daw'@'localhost' IDENTIFIED BY 'mugoc_1daw';
CREATE USER 'pearj_1daw'@'localhost' IDENTIFIED BY 'pearj_1daw';CREATE DATABASE bdpearju_1daw;
GRANT ALL PRIVILEGES ON bdpearju_1daw.* TO 'pearj_1daw'@'localhost' IDENTIFIED BY 'pearj_1daw';
CREATE USER 'qumoj_1daw'@'localhost' IDENTIFIED BY 'qumoj_1daw';CREATE DATABASE bdqumojo_1daw;
GRANT ALL PRIVILEGES ON bdqumojo_1daw.* TO 'qumoj_1daw'@'localhost' IDENTIFIED BY 'qumoj_1daw';
CREATE USER 'romom_1daw'@'localhost' IDENTIFIED BY 'romom_1daw';CREATE DATABASE bdromoma_1daw;
GRANT ALL PRIVILEGES ON bdromoma_1daw.* TO 'romom_1daw'@'localhost' IDENTIFIED BY 'romom_1daw';
CREATE USER 'rualj_1daw'@'localhost' IDENTIFIED BY 'rualj_1daw';CREATE DATABASE bdrualja_1daw;
GRANT ALL PRIVILEGES ON bdrualja_1daw.* TO 'rualj_1daw'@'localhost' IDENTIFIED BY 'rualj_1daw';
CREATE USER 'sasap_1daw'@'localhost' IDENTIFIED BY 'sasap_1daw';CREATE DATABASE bdsasapa_1daw;
GRANT ALL PRIVILEGES ON bdsasapa_1daw.* TO 'sasap_1daw'@'localhost' IDENTIFIED BY 'sasap_1daw';
CREATE USER 'satel_1daw'@'localhost' IDENTIFIED BY 'satel_1daw';CREATE DATABASE bdsatelu_1daw;
GRANT ALL PRIVILEGES ON bdsatelu_1daw.* TO 'satel_1daw'@'localhost' IDENTIFIED BY 'satel_1daw';
CREATE USER 'tovev_1daw'@'localhost' IDENTIFIED BY 'tovev_1daw';CREATE DATABASE bdtoveve_1daw;
GRANT ALL PRIVILEGES ON bdtoveve_1daw.* TO 'tovev_1daw'@'localhost' IDENTIFIED BY 'tovev_1daw';
CREATE USER 'varoa_1daw'@'localhost' IDENTIFIED BY 'varoa_1daw';CREATE DATABASE bdvaroal_1daw;
GRANT ALL PRIVILEGES ON bdvaroal_1daw.* TO 'varoa_1daw'@'localhost' IDENTIFIED BY 'varoa_1daw';
CREATE USER 'vemua_1daw'@'localhost' IDENTIFIED BY 'vemua_1daw';CREATE DATABASE bdvemual_1daw;
GRANT ALL PRIVILEGES ON bdvemual_1daw.* TO 'vemua_1daw'@'localhost' IDENTIFIED BY 'vemua_1daw';
